export const Data = [
  {
    question: "നോമ്പുകാരൻ പ്രവേശിക്കുന്ന സ്വർഗ കവാടമേത് ?",
    optionA: "Dark Army",
    optionB: "Death Squad",
    optionC: "റയ്യാൻ",
    optionD: "Army of Darkness",
    answer: "c",
  },
  {
    question: " ഖുർആനിൽ ഏറ്റവുമധികം പരാമർശിക്കപ്പെട്ട പ്രവാചകനാര് ?",
    optionA: "മുഹമ്മദ് നബി (സ)",
    optionB: "മൂസാനബി ( അ )",
    optionC: "ഈസാനബി  ( അ )",
    optionD: "ഇബ്രാഹീം  നബി  ( അ )",
    answer: "b",
  },
  {
    question: "പിതാവും പിതാമഹനും പിതാമഹന്റെ പിതാവും പ്രവാചകനായ ഏക പ്രവാചകനാര് ?",
    optionA: "ഇബ്രാഹീം  നബി  ( അ )",
    optionB: "മൂസാനബി ( അ )",
    optionC: "ഈസാനബി  ( അ )",
    optionD: "യൂസഫ് നബി ( അ )",
    answer: "d",
  },
  {
    question: "യൗമുൽ ഫുർഖാൻ എന്ന് വിശേഷിപ്പിക്കപ്പെട്ട ദിനം ഏത് ?",
    optionA: "ബദർ യുദ്ധ ദിനം",
    optionB: "അറഫ ദിനം ",
    optionC: "മക്കം ഫതഹ് ",
    optionD: "ലൈലത്തുൽ ഖദ്ർ ",
    answer: "a",
  },
  {
    question: "അല്ലാഹുവിന്റെ വാൾ ( സൈഫുള്ള ) എന്നപേരിൽ അറിയപ്പെട്ട സ്വഹാബിയാര് ?",
    optionA: "ഉസ്മാൻ ബിൻ അഫാൻ ( റ )",
    optionB: "അലി (റ)",
    optionC: "ഖാലിദ് ബിൻ വലീദ് ( റ )",
    optionD: "അബൂബക്കർ (റ)",
    answer: "c",
  },
  {
    question: " ഖുർആനിൽ പേര് പറയപ്പെട്ട ഏക വനിത ആര് ?",
    optionA: "ആമിന ബീവി (റ)",
    optionB: "ഹാജറ ബീവി (റ)",
    optionC: "മറിയംബീവി",
    optionD: "ആയിഷ ബീവി (റ)",
    answer: "c",
  },
  {
    question: "അസ്ഹാബുൽ ഖഹ്ഫിന്റെ മാതൃരാജ്യം ഏത് ?",
    optionA: "മദ് യൻ",
    optionB: "അഫ്സൂസ്",
    optionC: "സമൂദ് ഗോത്രം",
    optionD: "ആദ് സമുദായം",
    answer: "b",
  },
  {
    question: "സയ്യിദുൽ അൻസാർ എന്നറിയപ്പെടുന്ന സ്വഹാബിയാര് ?",
    optionA: "അബൂബക്കർ സിദ്ദീഖ്  (റ)",
    optionB: "ഉസ്മാൻ (റ)",
    optionC: "സഹ്ദ് ബിൻ മുആദ് ( റ )",
    optionD: "സൈദ് ബിൻ സാബിത് ( റ )",
    answer: "c",
  },
  {
    question: "ഖുർആനിൽ മക്കിയായ സൂറത്തുകൾ എത്ര ?",
    optionA: "114",
    optionB: "86",
    optionC: "30",
    optionD: "28",
    answer: "b",
  },
  {
    question: "ഖഹ്ബക്ക് ഉള്ളിൽ പ്രസവിച്ച സ്വഹാബിയാര് ?",
    optionA: "മാരിയ്യത്തുൽ ഖിബിതിയ്യ ( റ )",
    optionB: "ഖദീജ ( റ )",
    optionC: "ഉമ്മുസലമ ( റ )",
    optionD: "ഹഖിമിബിനു ഹിസാം ( റ )",
    answer: "d",
  },
  {
    question:
      "ഷുഹൈബ് നബിയെ നിയോഗിക്കപ്പെട്ട നാട് ഏത് ?",
    optionA: "യസ് രിബ്",
    optionB: "മദ് യൻ (മദായിൻ)",
    optionC: "ഈജിപ്‌",
    optionD: "ഉബാർ ",
    answer: "b",
  },
  {
    question:
      "നബി ( സ ) വഹ് യ് അടിസ്ഥാനത്തിൽ വിവാഹം ചെയ്ത പത്നിയാര് ?",
    optionA: "ഉമ്മുസലമ ( റ )"",
	optionB: "മാരിയ്യത്തുൽ ഖിബിതിയ്യ ( റ )",
	optionC: "ആയിഷ (റ)",
    optionD: "സൈനബ് ബിൻത് ജാഹ്ശ് ",
    answer: "d",
  },
  {
    question: "നബി ( സ ) ആദ്യമായി പങ്കെടുത്ത യുദ്ധം ഏത് ?",
    optionA: "ബദർ യുദ്ധം ",
    optionB: "ഹർബുൽ ഫിജാർ",
    optionC: "ഖൻദഖ് യുദ്ധം",
    optionD: "ഉഹ്ദ് യുദ്ധം",
    answer: "b",
  },
  {
    question: "ഖുർആനിൽ "ف" എന്ന അക്ഷരം ഇല്ലാത്തത് ഏത് സൂറത്തിലാണ് ?",
    optionA: "സൂറത്തുൽ കഹ്ഫ് ",
    optionB: "സൂറത്തുൽ ബക്കറ ",
    optionC: "സൂറത്തുൽ ഫാത്തിഹ",
    optionD: "സൂറത്തുൽ ആലു ഇമ്രാൻ ",
    answer: "c",
  },
  {
    question: "നബി ( സ ) യുടെ വഹ് യ് എഴുത്തുകാരനായ സ്വഹാബിയാരാണ് ?",
    optionA: "ഖാലിദ് ബിൻ വലീദ് (റ)",
    optionB: "ഹംസ ( റ )",
    optionC: "സൈദ് ബിൻ ഹാരിസ് ( റ )",
    optionD: "സൈദ് ബിനു സാബിത് ( റ )",
    answer: "d",
  },
  {
    question: "മദീനയുടെ പഴയ പേര് എന്ത് ?",
    optionA: "അഫ്‌സൂസ്",
    optionB: "മുഹാജിർ ",
    optionC: "ഉമ്മുൽ ഖുറ",
    optionD: "യസ് രിബ്",
    answer: "d",
  },
  {
    question: "ഖുർആനിലെ ഒരു സൂറത്തിലെ എല്ലാ ആയത്തിലും الله എന്ന പദമുള്ള സൂറത്ത് ഏത് ?",
    optionA: "സൂറത്ത് മുജാദല",
    optionB: "സൂറത്തുൽ കഹ്ഫ്",
    optionC: "സൂറത്തുൽ ആലു ഇമ്രാൻ",
    optionD: "സൂറത്ത് മര്‍യം",
    answer: "a",
  },
  {
    question: "നബി (സ ) ക്ക് ഇബ്രാഹിം എന്ന കുട്ടി ജനിച്ചത് ഏത് പത്നിയിലൂടെയാണ് ?",
    optionA: "ഖദീജ ( റ )",
    optionB: "മാരിയ്യത്തുൽ ഖിബിതിയ്യ (റ )",
    optionC: "ഉമ്മുസലമ ( റ )",
    optionD: "ആയിഷ (റ)",
    answer: "b",
  },
  {
    question: "അറബിയിലെ എല്ലാ അക്ഷരങ്ങളും ഉൾകൊള്ളുന്ന ഖുർആനിലെ രണ്ട് ആയത്തുകൾ ഏത് ?",
    optionA: "ആലുമ്രാൻ 152",
    optionB: "ഫത്ഹ്  29",
    optionC: "ആലുമ്രാൻ 154",
    optionD: "ഫത്ഹ് 27",
    answer: "c",
  },
  {
    question:
      "നബി ( സ ) പങ്കെടുത്ത അവസാന യുദ്ധം ഏത് ?",
    optionA: "തബുക് യുദ്ധം",
    optionB: "യമാമ യുദ്ധം",
    optionC: "ഹാർബറുൽ ഫിജാർ",
    optionD: "ദാതുര്‍രിഖാഅ്",
    answer: "a",
  },
   {
    question: "മക്കയുടെ മറ്റു രണ്ട് പേരുകൾ ഏതൊക്കെയാണ് ?",
    optionA: "Dark Army",
    optionB: "യസ് രിബ്,  ബക്ക",
    optionC: " ബക്ക ,  ഉമ്മുൽ ഖുറ",
    optionD: "Army of Darkness",
    answer: "c",
  },
  {
    question: "നോമ്പ് നിർബന്ധമാക്കപ്പെട്ട ഹിജ്‌റ വർഷം ഏത് ?",
    optionA: "ഹിജ്‌റ പത്താം വർഷം",
    optionB: "ഹിജ്‌റ രണ്ടാം വർഷം",
    optionC: "ഹിജ്‌റ ഒന്നാം വർഷം",
    optionD: "ഹിജ്‌റക്ക് മുൻപ് ",
    answer: "b",
  },
  {
    question: "ഖുർആൻ മനഃപാഠമുള്ള സ്വഹാബികൾ കൂടുതലായി ശഹീദായ യുദ്ധം ഏത് ?",
    optionA: "അഹ്സാബ് യുദ്ധം",
    optionB: "ഹാർബറുൽ ഫിജാർ",
    optionC: "തബുക് യുദ്ധം",
    optionD: " യമാമ യുദ്ധം",
    answer: "d",
  },
  {
    question: "സജദയുടെ ആദ്യ ആയത്ത് ഏത് സൂറത്തിലാണ് ?   ",
    optionA: "സൂറത്ത് അഹ്റാഫ്",
    optionB: "Monster",
    optionC: "Mistake",
    optionD: "Mentor",
    answer: "a",
  },
  {
    question: "ഉമ്മുൽ മസാകീൻ എന്നറിയപ്പെടുന്ന വനിത ആര് ?",
    optionA: "ഖദീജ   ( റ )",
    optionB: "മാരിയത്തുൽ ഖിബിതിയ്യ  ( റ )",
    optionC: "സൈനബ് ( റ )",
    optionD: "ഉമ്മു അയ്മൻ  ( റ )",
    answer: "c",
  },
  {
    question: "രണ്ട് മക്കളും പ്രവാചകനായ പ്രവാചകൻ ആര് ?",
    optionA: "മൂസ നബി ( അ )",
    optionB: "ലൂഥ് നബി ( അ )",
    optionC: "ഇബ്രാഹിം നബി (അ)",
    optionD: "യൂസഫ് നബി ( അ )",
    answer: "c",
  },
  {
    question: "നബിയുടെ വളർത്തുമ്മയുടെ പേരെന്ത് ?",
    optionA: "His father was angry at him and pushed him",
    optionB: "ഉമ്മു അയ്മൻ",
    optionC: "He saw Mr Robot and thought he wanted to hurt him",
    optionD: "He tripped while trying to escape his mother",
    answer: "b",
  },
  {
    question: " ഉമർ ( റ ) യുടെ ഘാതകൻ ആര് ?",
    optionA: "ഇബിൻ മുൽജിം",
    optionB: "ഇബിൻ അൽ സൗദ",
    optionC: "അബു ലുഹ് ലത്",
    optionD: "USA lost its footing as a global superpower",
    answer: "c",
  },
  {
    question: "പുരുഷന്മാരിൽ ആദ്യം ഇസ്ലാം ആശ്ലേശിച്ചതാര് ?",
    optionA: "അലി   ( റ )",
    optionB: "അബൂബക്കർ സ്വിദ്ധീഖ് ( റ )",
    optionC: "ഉമർ (റ)",
    optionD: "ഉസ്മാൻ (റ)",
    answer: "b",
  },
  {
    question: "ഖുർആനിലെ മദനി സൂറത്തുക്കളെ എണ്ണമെത്ര ?",
    optionA: "86",
    optionB: "30",
    optionC: "28",
    optionD: "114",
    answer: "c",
  },
  {
    question: " ഖുർആനിൽ പരാമർശിക്കപ്പെട്ട നബിമാരുടെ എണ്ണം എത്ര ?",
    optionA: "5",
    optionB: "25",
    optionC: "30",
    optionD: "70",
    answer: "b",
  },
  {
    question: "നബി ( സ ) യുടെ മാതാവ് മരണപ്പെട്ട സ്ഥലം  ?",
    optionA: "മക്ക",
    optionB: "അഫ്‌സൂസ്",
    optionC: "മദീന",
    optionD: "അബവാഹ്",
    answer: "d",
  },
  {
    question: "സയ്യിദു ശുഹദാഹ് എന്നറിയപ്പെടുന്ന സ്വഹാബിയാര് ?",
    optionA: "ഹംസ ( റ )",
    optionB: "അലി   റ )"",
    optionC: "ഉസ്മാൻ (റ)",
    optionD: "ഉമർ (റ)",
    answer: "a",
  },
  {
    question: "ഇബ്രാഹിം നബിയുടെ കാലത്തുണ്ടായിരുന്ന മറ്റൊരു റസൂൽ ?",
    optionA: "യൂസഫ് നബി",
    optionB: "ഹൂദ് നബി",
    optionC: "ലൂഥ് നബി ( അ )",
    optionD: "ശുഐബ് നബി",
    answer: "c",
  },
  {
    question: " ആദ് സമുദായത്തിലേക്ക് നിയോഗിക്കപ്പെട്ട പ്രവാചകനാര്?",
    optionA: "ശുഐബ് നബി  ( അ )",
    optionB: "യൂസഫ് നബി ( അ )"",
    optionC: "ഹൂദ് നബി ( അ )",
    optionD: "ലൂഥ് നബി ( അ )",
    answer: "c",
  },
  {
    question: "സ്വർഗത്തിൽ എന്റെ കൂട്ടുകാരൻ എന്ന് പ്രവാചകൻ പരിചയപ്പെടുത്തിയ സ്വഹാബിയാരാണ് ?",
    optionA: "അബൂബക്കർ സ്വിദ്ധീഖ് ( റ )",
    optionB: "ഉസ്മാൻ ബിൻ അഫാൻ",
    optionC: "ഹംസ ( റ )",
    optionD: "സഹ്ദ് ബിൻ മുആദ് ( റ )",
    answer: "b",
  },
  {
    question: "പ്രവാചകൻ ഹജ്ജിന് പുറപ്പെട്ടത് ഹിജ്‌റ എത്രാം വർഷമാണ് ?",
    optionA: "11",
    optionB: "9",
    optionC: "10",
    optionD: "8",
    answer: "c",
  },
  {
    question: "ഏത് സൂറത്തിലെ ആയത്തുകൾ കേട്ടാണ് ഉമർ ( റ ) ഇസ്ലാമിലേക്ക് കടന്ന് വന്നത് ?",
    optionA: "സൂറത്തുൽ മർയം",
    optionB: " സൂറത്ത് ത്വാഹാ",
    optionC: "സൂറത്ത് യാസീൻ",
    optionD: "സൂറത്തുൽ ഫാത്തിഹ",
    answer: "b",
  },
  {
    question: "അല്ലാഹു പരീക്ഷണാർത്ഥം ഒട്ടകത്തെ ഇറക്കപ്പെട്ടത് ഏത് സമുദായത്തിലേക്കാണ് ?",
    optionA: "ഉബാർ",
    optionB: "ആദ് സമുദായം",
    optionC: "മദ് യൻ",
    optionD: "സമൂദ് ഗോത്രം",
    answer: "d",
  },
  {
    question: "സ്വാഹിബുൽ ഫുതൂഹ് എന്നറിയപ്പെടുന്ന പ്രവാചകൻ ആര് ?",
    optionA: "യൂസഫ് നബി ( അ )",
    optionB: "ഇബ്രാഹീം നബി ( അ )",
    optionC: "യൂനുസ് നബി ( അ )",
    optionD: "ഹൂദ് നബി ( അ )",
    answer: "c",
  },
  {
    question: "  സ്വർഗത്തിൽ എല്ലാ കവാടങ്ങളിലൂടെയും ക്ഷണിക്കപ്പെടുന്ന സ്വഹാബിയാര് ?",
    optionA: "ഹംസ ( റ )",
    optionB: "അബൂബക്കർ സ്വിദ്ധീഖ് ( റ )",
    optionC: "ഉസ്മാൻ ബിൻ അഫാൻ ( റ )",
    optionD: "അലി (റ)",
	answer: "b",
  },
  {
    question: "ഖുർആനിൽ പറയപ്പെട്ട നരകത്തിലെ വൃക്ഷത്തിന്റെ പേര് എന്ത് ?",
    optionA: "Elliot's father sexually molested him",
    optionB: "Elliot's father never existed",
    optionC: "Elliot's father beat him",
    optionD: "സഖൂo",
    answer: "d",
  },
  {
    question: "നബി ( സ ) യുടെ വഫാത്തിന് ശേഷം ജീവിച്ചിരുന്ന ഏക സന്താനം ആര് ?",
    optionA: "ഫാത്തിമ ( റ )",
    optionB: "ഇബ്രാഹീം ",
    optionC: "Mistake",
    optionD: "Mentor",
    answer: "a",
  },
  {
    question: "ഉമ്മുൽ ഖുർആൻ എന്നറിയപ്പെടുന്ന സൂറത്ത് ഏത് ?",
    optionA: "സൂറത്ത് യാസീൻ",
    optionB: "സൂറത്ത് അൽ അലഖ്",
    optionC: "സൂറത്തുൽ ഫാത്തിഹ",
    optionD: "സൂറത്തുൽ മുൽക്ക് ",
    answer: "c",
  },
  {
    question: "ഖുർആനിൽ പേര് പറയപ്പെട്ട സ്വഹാബിയാര്?",
    optionA: "ഉസ്മാൻ ബിൻ അഫാൻ",
    optionB: "ഹംസ ( റ )",
    optionC: "സൈദ് ബിൻ ഹാരിസ് ( റ )",
    optionD: "സഹ്ദ് ബിൻ മുആദ് ( റ )",
    answer: "c",
  },
  {
    question: "ഖുർആനിൽ ആദ്യമായി അവതരിച്ച ആയത്തുകൾ ഏത് സൂറത്തിലാണ്  ?",
    optionA: "സൂറത്തുൽ ഫാത്തിഹ",
    optionB: "സൂറത്ത് അൽ അലഖ്",
    optionC: "സൂറത്ത് ത്വാഹാ",
    optionD: "സൂറത്ത് അന്നംല് ",
    answer: "b",
  },
  {
    question: "ഖുർആനിൽ രണ്ട് ബിസ്മിയുള്ള സൂറത്ത് ഏത് ?",
    optionA: "സൂറത്ത് അൽ അലഖ്",
    optionB: "സൂറത്ത് തൗബ",
    optionC: "സൂറത്ത് അന്നംല് ",
    optionD: " സൂറത്ത് ത്വാഹാ",
    answer: "c",
  },
  {
    question: "വിവാഹം കഴിക്കാത്ത പ്രവാചകനാരാണ് ?",
    optionA: "മൂസാ നബി ( അ )",
    optionB: "ഈസാനബി  ( അ )",
    optionC: "യൂസഫ് നബി ( അ )",
    optionD: "ശുഐബ് നബി",
    answer: "b",
  },
  {
    question: "ഖുർആനിൽ ബിസ്മിയില്ലാതെ തുടങ്ങുന്ന സൂറത്ത് ഏത് ?",
    optionA: "സൂറത്ത് അൽ അലഖ്",
    optionB: "സൂറത്ത് ത്വാഹാ",
    optionC: "സൂറത്ത് അന്നംല്",
    optionD: "സൂറത്ത് തൗബ",
    answer: "d",
  },
  
];
